### ISSUE TITLE
Can file format be overwritten?

### ISSUE THREAD

**Issue by michaelpporter** [ttscoff/journal-cli#3]
The colon in the naming conflicts with Obsidian sync.

`Ignoring remote file name with illegal characters Calendar/mood/entries/2023-09-12_16:01.md`

https://github.com/ttscoff/journal-cli/blob/18b03e9aa2e4ceaa2e5fc61136ef2465cb92ab0e/lib/journal-cli/checkin.rb#L124

or maybe a flag opion to set the date to `YYYMMDDHHmm`

**Comment by ttscoff** [comment]
Oh, I didn't realize this would be an issue. For sure I can change the filename to remove the colon.
