### ISSUE TITLE
Add a Celcius option for the weather api

### ISSUE THREAD

**Issue by mlogg** [ttscoff/journal-cli#4]
Unfortunately the default for the weather api is Fahrenheid. A configuration option for Celsius would be nice, the weather info is interesting.

**Comment by ttscoff** [comment]
I wondered how long it would take for this to be a request. Will have to add a config option for it.

**Comment by ttscoff** [comment]
Update to the latest release (`gem install journal-cli`) and you'll be able to add a `temp_in: c` key to your config (for Celsius). Defaults to Fahrenheit.

**Comment by larkov** [comment]
Closed my pull request as @ttscoff made a prettier solution.

**Comment by ttscoff** [comment]
Oh man, sorry, I didn't see there was a Pull Request waiting!

**Comment by larkov** [comment]
No worries. As I wrote your solution was prettier than mine when I looked at it. :) I'm not fluent in ruby.
