### ISSUE TITLE
Errors "did not find expected key while parsing a block mapping at line 1 column 1"

### ISSUE THREAD

**Issue by berlinde** [ttscoff/journal-cli#7]
Hi,

I'm very, very noob at this but feel I followed the instructions the best I could, but when trying to run something like `journal mood "yesterday 5pm"`, I get the following error:

`❯ journal mood "yesterday 5pm"
/Users/toze/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/psych-5.1.0/lib/psych/parser.rb:62:in `_native_parse': (<unknown>): did not find expected key while parsing a block mapping at line 1 column 1 (Psych::SyntaxError)
	from /Users/toze/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/psych-5.1.0/lib/psych/parser.rb:62:in `parse'
	from /Users/toze/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/psych-5.1.0/lib/psych.rb:455:in `parse_stream'
	from /Users/toze/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/psych-5.1.0/lib/psych.rb:399:in `parse'
	from /Users/toze/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/psych-5.1.0/lib/psych.rb:323:in `safe_load'
	from /Users/toze/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/psych-5.1.0/lib/psych.rb:369:in `load'
	from /Users/toze/.rvm/gems/ruby-3.2.2/gems/journal-cli-1.0.19/lib/journal-cli.rb:60:in `config'
	from /Users/toze/.rvm/gems/ruby-3.2.2/gems/journal-cli-1.0.19/bin/journal:36:in `run'
	from /Users/toze/.rvm/gems/ruby-3.2.2/gems/journal-cli-1.0.19/bin/journal:78:in `<top (required)>'
	from /Users/toze/.rvm/gems/ruby-3.2.2/bin/journal:25:in `load'
	from /Users/toze/.rvm/gems/ruby-3.2.2/bin/journal:25:in `<main>'
	from /Users/toze/.rvm/gems/ruby-3.2.2/bin/ruby_executable_hooks:22:in `eval'
	from /Users/toze/.rvm/gems/ruby-3.2.2/bin/ruby_executable_hooks:22:in `<main>'`

because it seems it could be a trailing or extra space in the yaml file so I manually removed all in vs code, that didn't make a difference but when running it through a yaml validator I got the following error:
`All mapping items must start at the same column at line x, column y`
which seems to be a templating issue, but I barely edited the file, so I'm a bit at a loss here. 

Can anyone shed some light on what I'm missing?

**Comment by ttscoff** [comment]
This is a YAML parsing error, I'd need to see your config to diagnose.
